FROM hapiproject/hapi:latest

ENV JDBC_URL=jdbc:postgresql://omop54:5432/omop54
ENV JDBC_USERNAME=postgres
ENV JDBC_PASSWORD=password
ENV SERVERBASE_URL=http://localhost:8080/omoponfhir/fhir
ENV SMART_INTROSPECTURL=http://localhost:8080/smart/introspect
ENV SMART_AUTHSERVERURL=http://localhost:8080/smart/authorize
ENV SMART_TOKENSERVERURL=http://localhost:8080/smart/token
ENV AUTH_BEARER=12345
ENV AUTH_BASIC=client:secret
ENV FHIR_READONLY=False
ENV MEDICATION_TYPE=code

EXPOSE 8080