FROM python:3.8
RUN mkdir /api 
COPY . /api
COPY pyproject.toml /api 
WORKDIR /api
ENV PYTHONPATH=${PYTHONPATH}:${PWD}

RUN pip3 install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev

EXPOSE 4000

CMD [ "poetry", "run", "flask", "run", "-p", "4000", "-h", "0.0.0.0", "--reload" ]